language: haskell
ghc:
  - "7.10.3"
  - "8.6.4"
os:
  - linux
notifications:
  email: false
install:
  - cabal sandbox init
  - cabal install --only-dependencies --enable-tests
script:
  - cabal configure --ghc-option=-Werror --enable-tests
  - cabal build
  - cabal test
sudo: false
